base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ml.urls'))
]

ml/urls.py
from django.urls import path
from . import views

app_name = 'ml'

urlpatterns = [
    path('', views.form, name='form')
]

ml/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Sentence(models.Model):
    sentence = models.CharField(max_length=255, default=None)
    is_good = models.BooleanField(default=None, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    
    class Meta():
        verbose_name = 'Sentence'
        verbose_name_plural = 'Sentences'

    def __str__(self) -> str:
        return self.sentence

ml/views.py
from django.shortcuts import render
from .models import Sentence

# Create your views here.
def form(request):
    sentences = Sentence.objects.order_by('-created_at').first()
    return render(request, 'ml/form.html', {'sentences':sentences})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title> {% block title%}
    {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href={% url 'ml:form'%} class="navbar-brand">Good or Not</a>
        </div>
    </nav>
    <main class="container">
        {% block content%}
        {% endblock %}
    <main>
</body>
</html>

templates/ml/form.html
{% extends "base.html" %}

{% block title %}Goodn't{%endblock %}

{% block content %}
<form > 
    <div class="mb-3 mt-3">
      <label for="exampleInputEmail1" class="form-label">Sentence to determine mood</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" 
      placeholder='For example: "{{sentences}}"'> 
    </div>
   
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Submit
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Here will be the verdict</h1> <!-- Сюда добавить вывод из скрипта -->
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {{sentences}} <!-- Вывод последнего добавленного сообщения в БД (вохможно костыльно) -->
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>



    <main class="mb-3">
      </p>
    </main>
  </form>
    
{% endblock %}